Models/ErrorViewModel.cs
namespace classwork.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/FileMod.cs
namespace classwork.Models;

public abstract class FileMod
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string FileType { get; set; }
    public string Extension { get; set; }
    public string Description { get; set; }
    public string? UploadedBy { get; set; }
    public DateTime? CreatedOn { get; set; }
}

Models/FileOnDatabaseModel.cs
namespace classwork.Models;
public class FileOnDatabaseModel : FileMod
{
    public byte[] Data { get; set; }
}

Models/FileOnFileSystemModel.cs
namespace classwork.Models;

public class FileOnFileSystemModel : FileMod
{
    public string FilePath { get; set; }
}

Models/FileUploadViewModel.cs
namespace classwork.Models;

public class FileUploadViewModel
{
    public List<FileOnFileSystemModel> FilesOnFileSystem { get; set; }
    public List<FileOnDatabaseModel> FilesOnDatabase { get; set; }
}

Controllers/FileController.cs
using classwork.ApplicationDbContext;
using classwork.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace classwork.Controllers;

public class FileController : Controller
{
private readonly ApplicationContext _context;
public FileController(ApplicationContext context)
{
    _context = context;
}
    public async Task<IActionResult> Index()
    {
        var fileuploadViewModel = await LoadAllFiles();
        ViewBag.Message = TempData["Message"];
        return View(fileuploadViewModel);
    }

    private async Task<FileUploadViewModel> LoadAllFiles()
    {
        var viewModel = new FileUploadViewModel();
        viewModel.FilesOnDatabase = await _context.FileOnDatabaseModels.ToListAsync();
        viewModel.FilesOnFileSystem = await _context.FileOnFileSystemModels.ToListAsync();
        return viewModel;
    }

    [HttpPost]
public async Task<IActionResult> UploadToFileSystem(List<IFormFile> files, string description)
{
    foreach(var file in files)
    {
        var basePath = Path.Combine(Directory.GetCurrentDirectory() + "\\Files\\");
        bool basePathExists = System.IO.Directory.Exists(basePath);
        if (!basePathExists) Directory.CreateDirectory(basePath);
        var fileName = Path.GetFileNameWithoutExtension(file.FileName);
        var filePath = Path.Combine(basePath, file.FileName);
        var extension = Path.GetExtension(file.FileName);
        if (!System.IO.File.Exists(filePath))
        {
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            var fileModel = new FileOnFileSystemModel
            {
                CreatedOn = DateTime.UtcNow,
                FileType = file.ContentType,
                Extension = extension,
                Name = fileName,
                Description = description,
                FilePath = filePath,
                UploadedBy = "Ade"
            };
            _context.FileOnFileSystemModels.Add(fileModel);
            _context.SaveChanges();
        }
    }

    TempData["Message"] = "File successfully uploaded to File System.";
    return RedirectToAction("Index");
}

public async Task<IActionResult> DownloadFileFromFileSystem(int id)
{

    var file = await _context.FileOnFileSystemModels.Where(x => x.Id == id).FirstOrDefaultAsync();
    if (file == null) return null;
    var memory = new MemoryStream();
    using (var stream = new FileStream(file.FilePath, FileMode.Open))
    {
        await stream.CopyToAsync(memory);
    }
    memory.Position = 0;
    return File(memory, file.FileType, file.Name + file.Extension);
}

public async Task<IActionResult> DeleteFileFromFileSystem(int id)
{

    var file = await _context.FileOnFileSystemModels.Where(x => x.Id == id).FirstOrDefaultAsync();
    if (file == null) return null;
    if (System.IO.File.Exists(file.FilePath))
    {
        System.IO.File.Delete(file.FilePath);
    }
    _context.FileOnFileSystemModels.Remove(file);
    _context.SaveChanges();
    TempData["Message"] = $"Removed {file.Name + file.Extension} successfully from File System.";
    return RedirectToAction("Index");
}



//Uploading to DataBase

[HttpPost]
public async Task<IActionResult> UploadToDatabase(List<IFormFile> files,string description)
{
    foreach (var file in files)
    {
        var fileName = Path.GetFileNameWithoutExtension(file.FileName);
        var extension = Path.GetExtension(file.FileName);
        var fileModel = new FileOnDatabaseModel
        {
            CreatedOn = DateTime.UtcNow,
            FileType = file.ContentType,
            Extension = extension,
            Name = fileName,
            Description = description
        };
        using (var dataStream = new MemoryStream())
        {
            await file.CopyToAsync(dataStream);
            fileModel.Data = dataStream.ToArray();
        }
        _context.FileOnDatabaseModels.Add(fileModel);
        _context.SaveChanges();
    }
    TempData["Message"] = "File successfully uploaded to Database";
    return RedirectToAction("Index");
}

public async Task<IActionResult> DownloadFileFromDatabase(int id)
{
    var file = await _context.FileOnDatabaseModels.Where(x => x.Id == id).FirstOrDefaultAsync();
    if (file == null) return null;
    return File(file.Data, file.FileType, file.Name+file.Extension);
}

public async Task<IActionResult> DeleteFileFromDatabase(int id)
{
    var file = await _context.FileOnDatabaseModels.Where(x => x.Id == id).FirstOrDefaultAsync();
    _context.FileOnDatabaseModels.Remove(file);
    _context.SaveChanges();
    TempData["Message"] = $"Removed {file.Name + file.Extension} successfully from Database.";
    return RedirectToAction("Index");
}

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using classwork.Models;

namespace classwork.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/File/Index.cshtml
@model FileUploadViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Start Uploading Files Here</h4>
<hr />
@if (ViewBag.Message != null)
{
    <div class="alert alert-success alert-dismissible" style="margin-top:20px">
        @ViewBag.Message
    </div>
}

<form method="post" enctype="multipart/form-data">
    <input type="file" name="files" multiple required />
    <input type="text" autocomplete="off" placeholder="Enter File Description" name="description" required />
    <button type="submit" class="btn btn-primary" asp-controller="File" asp-action="UploadToFileSystem">Upload to File System</button>
    <button class="btn btn-success" type="submit" asp-controller="File" asp-action="UploadToDatabase">Upload to Database</button>
    @* <br>
     <label asp-for = "FirstName" class = "control-label"></label>
            <input asp-for = "FirstName" class = "form-control" placeholder="Alexander"/>
            <span asp-validation-for="FirstName" class="text-danger"></span> *@
</form>

<hr />
<h4>Files on File System</h4>
@if (Model.FilesOnFileSystem.Count == 0)
{
    <caption>No Records Found</caption>
}
else
{
    <caption>List of Files on File System</caption>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th>File Type</th>
                <th>Created On</th>
                 <th>Uploaded By</th>
                <th>Action1</th>
                <th>Action2</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var file in Model.FilesOnFileSystem)
            {
                <tr>
                    <td>@file.Id</td>
                    <td>@file.Name</td>
                    <td>@file.Description</td>
                    <td>@file.FileType</td>
                    <td>@file.CreatedOn</td>
                     <td>@file.UploadedBy</td>
                    <td>
                        <a type="button" class="btn btn-primary" asp-controller="File" asp-action="DownloadFileFromFileSystem" asp-route-id="@file.Id">Download</a>
                        
                    </td>
                    <td>
                        <a type="button" class="btn btn-danger" asp-controller="File" asp-action="DeleteFileFromFileSystem" asp-route-id="@file.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}




@* Database *@
<hr />
<h4>Files on Database</h4>
@if (Model.FilesOnDatabase.Count == 0)
{
    <caption>No Records Found</caption>
}
else
{
    <caption>List of Files on Database</caption>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th>File Type</th>
                <th>Created On</th>
                 <th>Uploaded By</th>
                <th>Action1</th>
                <th>Action2</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var file in Model.FilesOnDatabase)
            {
                <tr>
                    <td>@file.Id</td>
                    <td>@file.Name</td>
                    <td>@file.Description</td>
                    <td>@file.FileType</td>
                    <td>@file.CreatedOn</td>
                     <td>@file.UploadedBy</td>
                    <td>
                        <a type="button" class="btn btn-primary" asp-controller="File" asp-action="DownloadFileFromDatabase" asp-route-id="@file.Id">Download</a>
                        
                    </td>
                    <td>
                        <a type="button" class="btn btn-danger" asp-controller="File" asp-action="DeleteFileFromDatabase" asp-route-id="@file.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - classwork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/classwork.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">classwork</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Index">Upload File</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - classwork - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>